### ISSUE TITLE
Official documentation link in README doesn't work

### ISSUE THREAD

**Issue by cnpryer** [nextmv-io/nextroute#70]
The link to _the official documentation_ in the README seems dead (https://www.nextmv.io/docs/vehicle-routing).

https://github.com/nextmv-io/nextroute/blob/27a581b69a52ce9b634dab7c785bbb19901bcd8b/README.md?plain=1#L87-L89

Should this point to https://www.nextmv.io/docs/use-cases/vehicle-routing/get-started now?

**Comment by merschformann** [comment]
Thanks for finding the broken link! :hugs: 
Added a quick fix in #71 .
